///* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
///* Header for class tl_com_testmaterialdesign_navigation9_MyJniClass */
//
//#ifndef _Included_tl_com_testmaterialdesign_navigation9_MyJniClass
//#define _Included_tl_com_testmaterialdesign_navigation9_MyJniClass
//#ifdef __cplusplus
//extern "C" {
//#endif
///*
// * Class:     tl_com_testmaterialdesign_navigation9_MyJniClass
// * Method:    sum java里调用c语言函数求和并返回给java
// * Signature: (II)I
// */
//JNIEXPORT jint JNICALL Java_tl_com_testmaterialdesign_navigation9_MyJniClass_sum
//  (JNIEnv *, jobject, jint, jint);
//
///*
// * Class:     tl_com_testmaterialdesign_navigation9_MyJniClass
// * Method:    append java里调用c语言函数添加字符串并返回给java
// * Signature: (Ljava/lang/String;)Ljava/lang/String;
// */
//JNIEXPORT jstring JNICALL Java_tl_com_testmaterialdesign_navigation9_MyJniClass_append
//  (JNIEnv *, jobject, jstring);
//
///*
// * Class:     tl_com_testmaterialdesign_navigation9_MyJniClass
// * Method:    operateEle java里调用c语言函数操作数组，并将数组返回
// * Signature: ([I)[I
// */
//JNIEXPORT jintArray JNICALL Java_tl_com_testmaterialdesign_navigation9_MyJniClass_operateEle
//  (JNIEnv *, jobject, jintArray);
//
///*
// * Class:     tl_com_testmaterialdesign_navigation9_MyJniClass
// * Method:    checkPwd java调用c语言函数校验密码并返回boolean值
// * Signature: (Ljava/lang/String;)Z
// */
//JNIEXPORT jboolean JNICALL Java_tl_com_testmaterialdesign_navigation9_MyJniClass_checkPwd
//  (JNIEnv *, jobject, jstring);
//
///*
// * Class:     tl_com_testmaterialdesign_navigation9_MyJniClass
// * Method:    callbackAdd java触发c语言函数，c语言函数里调用java函数
// * Signature: ()V
// */
//JNIEXPORT void JNICALL Java_tl_com_testmaterialdesign_navigation9_MyJniClass_callbackAdd
//  (JNIEnv *, jobject);
//
///*
// * Class:     tl_com_testmaterialdesign_navigation9_MyJniClass
// * Method:    callbackHelloFromJava java触发c语言函数，c语言函数里调用java函数
// * Signature: ()V
// */
//JNIEXPORT void JNICALL Java_tl_com_testmaterialdesign_navigation9_MyJniClass_callbackHelloFromJava
//  (JNIEnv *, jobject);
//
///*
// * Class:     tl_com_testmaterialdesign_navigation9_MyJniClass
// * Method:    callbackPrintString java触发c语言函数，c语言函数里调用java函数
// * Signature: ()V
// */
//JNIEXPORT void JNICALL Java_tl_com_testmaterialdesign_navigation9_MyJniClass_callbackPrintString
//  (JNIEnv *, jobject);
//
///*
// * Class:     tl_com_testmaterialdesign_navigation9_MyJniClass
// * Method:    callbackSayHello java触发c语言函数，c语言函数里调用java函数
// * Signature: ()V
// */
//JNIEXPORT void JNICALL Java_tl_com_testmaterialdesign_navigation9_MyJniClass_callbackSayHello
//  (JNIEnv *, jobject);
//
//#ifdef __cplusplus
//}
//#endif
//#endif
